/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// ActivePeriod : Start and End dates for active alert



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivePeriod {
    /// Start Date. Format is ISO8601.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    /// End Date. Format is ISO8601.
    #[serde(rename = "end", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end: Option<Option<String>>,
}

impl ActivePeriod {
    /// Start and End dates for active alert
    pub fn new() -> ActivePeriod {
        ActivePeriod {
            start: None,
            end: None,
        }
    }
}


