/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// Alerts : A page of [AlertResource](#alertresource) results



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Alerts {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RoutePatternsLinks>>,
    /// Content with [AlertResource](#alertresource) objects
    #[serde(rename = "data")]
    pub data: Vec<crate::models::AlertResource>,
}

impl Alerts {
    /// A page of [AlertResource](#alertresource) results
    pub fn new(data: Vec<crate::models::AlertResource>) -> Alerts {
        Alerts {
            links: None,
            data,
        }
    }
}


