/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertResourceRelationships {
    #[serde(rename = "facility", skip_serializing_if = "Option::is_none")]
    pub facility: Option<Box<crate::models::AlertResourceRelationshipsFacility>>,
}

impl AlertResourceRelationships {
    pub fn new() -> AlertResourceRelationships {
        AlertResourceRelationships {
            facility: None,
        }
    }
}


