/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// BadRequestErrorsInner : A JSON-API error when a bad request is received



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestErrorsInner {
    /// The HTTP status code applicable to the problem
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<crate::models::BadRequestErrorsInnerSource>>,
    /// A short, human-readable summary of the problem
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// An application-specific error code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl BadRequestErrorsInner {
    /// A JSON-API error when a bad request is received
    pub fn new() -> BadRequestErrorsInner {
        BadRequestErrorsInner {
            status: None,
            source: None,
            detail: None,
            code: None,
        }
    }
}


