/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// FacilityProperty : Name/value pair for additional facility information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacilityProperty {
    /// The name of the property
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl FacilityProperty {
    /// Name/value pair for additional facility information
    pub fn new() -> FacilityProperty {
        FacilityProperty {
            name: None,
        }
    }
}


