/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// Forbidden : A JSON-API error document when the API key is invalid



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Forbidden {
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::ForbiddenErrorsInner>,
}

impl Forbidden {
    /// A JSON-API error document when the API key is invalid
    pub fn new(errors: Vec<crate::models::ForbiddenErrorsInner>) -> Forbidden {
        Forbidden {
            errors,
        }
    }
}


