/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// ForbiddenErrorsInner : A JSON-API error when an invalid API key is received



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForbiddenErrorsInner {
    /// The HTTP status code applicable to the problem
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// An application-specific error code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl ForbiddenErrorsInner {
    /// A JSON-API error when an invalid API key is received
    pub fn new() -> ForbiddenErrorsInner {
        ForbiddenErrorsInner {
            status: None,
            code: None,
        }
    }
}


