/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// LiveFacilities : A page of [LiveFacilityResource](#livefacilityresource) results



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiveFacilities {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RoutePatternsLinks>>,
    /// Content with [LiveFacilityResource](#livefacilityresource) objects
    #[serde(rename = "data")]
    pub data: Vec<crate::models::LiveFacilityResource>,
}

impl LiveFacilities {
    /// A page of [LiveFacilityResource](#livefacilityresource) results
    pub fn new(data: Vec<crate::models::LiveFacilityResource>) -> LiveFacilities {
        LiveFacilities {
            links: None,
            data,
        }
    }
}


