/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// NotFound : A JSON-API error document when a resource is not found



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFound {
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::NotFoundErrorsInner>,
}

impl NotFound {
    /// A JSON-API error document when a resource is not found
    pub fn new(errors: Vec<crate::models::NotFoundErrorsInner>) -> NotFound {
        NotFound {
            errors,
        }
    }
}


