/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// NotFoundErrorsInner : A JSON-API error when a resource is not found



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFoundErrorsInner {
    /// A short, human-readable summary of the problem
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The HTTP status code applicable to the problem
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<crate::models::NotFoundErrorsInnerSource>>,
    /// An application-specific error code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl NotFoundErrorsInner {
    /// A JSON-API error when a resource is not found
    pub fn new() -> NotFoundErrorsInner {
        NotFoundErrorsInner {
            title: None,
            status: None,
            source: None,
            code: None,
        }
    }
}


