/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// NotFoundErrorsInnerSource : A JSON-API error source



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotFoundErrorsInnerSource {
    /// The name of parameter that was used to lookup up the resource that was not found
    #[serde(rename = "parameter", skip_serializing_if = "Option::is_none")]
    pub parameter: Option<String>,
}

impl NotFoundErrorsInnerSource {
    /// A JSON-API error source
    pub fn new() -> NotFoundErrorsInnerSource {
        NotFoundErrorsInnerSource {
            parameter: None,
        }
    }
}


