/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// NotAcceptable : A JSON-API error document when a request uses an invalid 'accept' header



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotAcceptable {
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::NotAcceptableErrorsInner>,
}

impl NotAcceptable {
    /// A JSON-API error document when a request uses an invalid 'accept' header
    pub fn new(errors: Vec<crate::models::NotAcceptableErrorsInner>) -> NotAcceptable {
        NotAcceptable {
            errors,
        }
    }
}


