/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutePatternResourceRelationshipsRepresentativeTripLinks {
    /// Relationship link for representative_trip
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
    /// Related representative_trip link
    #[serde(rename = "related", skip_serializing_if = "Option::is_none")]
    pub related: Option<String>,
}

impl RoutePatternResourceRelationshipsRepresentativeTripLinks {
    pub fn new() -> RoutePatternResourceRelationshipsRepresentativeTripLinks {
        RoutePatternResourceRelationshipsRepresentativeTripLinks {
            param_self: None,
            related: None,
        }
    }
}


