/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// Routes : A page of [RouteResource](#routeresource) results



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Routes {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RoutePatternsLinks>>,
    /// Content with [RouteResource](#routeresource) objects
    #[serde(rename = "data")]
    pub data: Vec<crate::models::RouteResource>,
}

impl Routes {
    /// A page of [RouteResource](#routeresource) results
    pub fn new(data: Vec<crate::models::RouteResource>) -> Routes {
        Routes {
            links: None,
            data,
        }
    }
}


