/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// RoutePatterns : A page of [RoutePatternResource](#routepatternresource) results



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutePatterns {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RoutePatternsLinks>>,
    /// Content with [RoutePatternResource](#routepatternresource) objects
    #[serde(rename = "data")]
    pub data: Vec<crate::models::RoutePatternResource>,
}

impl RoutePatterns {
    /// A page of [RoutePatternResource](#routepatternresource) results
    pub fn new(data: Vec<crate::models::RoutePatternResource>) -> RoutePatterns {
        RoutePatterns {
            links: None,
            data,
        }
    }
}


