/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// RoutePatternResource : Information about the different variations of service that may be run within a single route_id, including when and how often they are operated. See [GTFS `route_patterns.txt](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#route_patternstxt) for the base specification. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutePatternResource {
    /// The JSON-API resource type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "relationships", skip_serializing_if = "Option::is_none")]
    pub relationships: Option<Box<crate::models::RoutePatternResourceRelationships>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<serde_json::Value>,
    /// The JSON-API resource ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::RoutePatternResourceAttributes>>,
}

impl RoutePatternResource {
    /// Information about the different variations of service that may be run within a single route_id, including when and how often they are operated. See [GTFS `route_patterns.txt](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#route_patternstxt) for the base specification. 
    pub fn new() -> RoutePatternResource {
        RoutePatternResource {
            r#type: None,
            relationships: None,
            links: None,
            id: None,
            attributes: None,
        }
    }
}


