/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutePatternResourceRelationships {
    #[serde(rename = "route", skip_serializing_if = "Option::is_none")]
    pub route: Option<Box<crate::models::TripResourceRelationshipsRoute>>,
    #[serde(rename = "representative_trip", skip_serializing_if = "Option::is_none")]
    pub representative_trip: Option<Box<crate::models::RoutePatternResourceRelationshipsRepresentativeTrip>>,
}

impl RoutePatternResourceRelationships {
    pub fn new() -> RoutePatternResourceRelationships {
        RoutePatternResourceRelationships {
            route: None,
            representative_trip: None,
        }
    }
}


