/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutePatternsLinks {
    /// Link to this page of results
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
    /// Link to the previous page of results
    #[serde(rename = "prev", skip_serializing_if = "Option::is_none")]
    pub prev: Option<String>,
    /// Link to the next page of results
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// Link to the last page of results
    #[serde(rename = "last", skip_serializing_if = "Option::is_none")]
    pub last: Option<String>,
    /// Link to the first page of results
    #[serde(rename = "first", skip_serializing_if = "Option::is_none")]
    pub first: Option<String>,
}

impl RoutePatternsLinks {
    pub fn new() -> RoutePatternsLinks {
        RoutePatternsLinks {
            param_self: None,
            prev: None,
            next: None,
            last: None,
            first: None,
        }
    }
}


