/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// Schedules : A page of [ScheduleResource](#scheduleresource) results



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Schedules {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RoutePatternsLinks>>,
    /// Content with [ScheduleResource](#scheduleresource) objects
    #[serde(rename = "data")]
    pub data: Vec<crate::models::ScheduleResource>,
}

impl Schedules {
    /// A page of [ScheduleResource](#scheduleresource) results
    pub fn new(data: Vec<crate::models::ScheduleResource>) -> Schedules {
        Schedules {
            links: None,
            data,
        }
    }
}


