/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// Services : A page of [ServiceResource](#serviceresource) results



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Services {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RoutePatternsLinks>>,
    /// Content with [ServiceResource](#serviceresource) objects
    #[serde(rename = "data")]
    pub data: Vec<crate::models::ServiceResource>,
}

impl Services {
    /// A page of [ServiceResource](#serviceresource) results
    pub fn new(data: Vec<crate::models::ServiceResource>) -> Services {
        Services {
            links: None,
            data,
        }
    }
}


