/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// Shapes : A page of [ShapeResource](#shaperesource) results



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Shapes {
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::RoutePatternsLinks>>,
    /// Content with [ShapeResource](#shaperesource) objects
    #[serde(rename = "data")]
    pub data: Vec<crate::models::ShapeResource>,
}

impl Shapes {
    /// A page of [ShapeResource](#shaperesource) results
    pub fn new(data: Vec<crate::models::ShapeResource>) -> Shapes {
        Shapes {
            links: None,
            data,
        }
    }
}


