/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StopResourceRelationships {
    #[serde(rename = "parent_station", skip_serializing_if = "Option::is_none")]
    pub parent_station: Option<Box<crate::models::StopResourceRelationshipsParentStation>>,
}

impl StopResourceRelationships {
    pub fn new() -> StopResourceRelationships {
        StopResourceRelationships {
            parent_station: None,
        }
    }
}


