/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// TooManyRequests : A JSON-API error document when rate limited



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TooManyRequests {
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::TooManyRequestsErrorsInner>,
}

impl TooManyRequests {
    /// A JSON-API error document when rate limited
    pub fn new(errors: Vec<crate::models::TooManyRequestsErrorsInner>) -> TooManyRequests {
        TooManyRequests {
            errors,
        }
    }
}


