/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */

/// TooManyRequestsErrorsInner : A JSON-API error when rate limited



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TooManyRequestsErrorsInner {
    /// The HTTP status code applicable to the problem
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Human-readable summary of the problem
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// An application-specific error code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl TooManyRequestsErrorsInner {
    /// A JSON-API error when rate limited
    pub fn new() -> TooManyRequestsErrorsInner {
        TooManyRequestsErrorsInner {
            status: None,
            detail: None,
            code: None,
        }
    }
}


