/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TripResourceRelationshipsRoutePatternData {
    /// Type of related route_pattern resource
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Related route_pattern resource id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl TripResourceRelationshipsRoutePatternData {
    pub fn new() -> TripResourceRelationshipsRoutePatternData {
        TripResourceRelationshipsRoutePatternData {
            r#type: None,
            id: None,
        }
    }
}


