/*
 * MBTA
 *
 * MBTA service API. https://www.mbta.com Source code: https://github.com/mbta/api
 *
 * The version of the OpenAPI document: 3.0
 * Contact: developer@mbta.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VehicleResourceRelationships {
    #[serde(rename = "trip", skip_serializing_if = "Option::is_none")]
    pub trip: Option<Box<crate::models::ScheduleResourceRelationshipsTrip>>,
    #[serde(rename = "stop", skip_serializing_if = "Option::is_none")]
    pub stop: Option<Box<crate::models::ScheduleResourceRelationshipsStop>>,
    #[serde(rename = "route", skip_serializing_if = "Option::is_none")]
    pub route: Option<Box<crate::models::TripResourceRelationshipsRoute>>,
}

impl VehicleResourceRelationships {
    pub fn new() -> VehicleResourceRelationships {
        VehicleResourceRelationships {
            trip: None,
            stop: None,
            route: None,
        }
    }
}


